version: '3.8'

services:

  db:
    container_name: mongo-dev
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: financials
    ports:
      - '27017:27017'
    volumes:
      - ./db:/db-dump
      - ./db/data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro